version = 0.1

[default.deploy.parameters]
stack_name = "aws-sam-textract-cv-processor"
resolve_s3 = true
s3_prefix = "aws-sam-textract-cv-processor"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
